# Configuración por defecto para el mod Rogue.

[combat]
# Bonificación de daño cuando una afinidad contrarresta a la otra.
affinityBonusPercent = 25

[dungeons]
# Número máximo de enemigos vivos por defecto.
maxAliveDefault = 12
# Tiempo límite por sala en segundos.
roomTimeLimitSeconds = 300

[debug]
# Activa mensajes extra de depuración.
logVerbose = true
