modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="rpg_mobs_pack_1"
version="${version}"
displayName="RPG Mobs Pack 1"
description='''Contenido de mobs (placeholder)'''
[[dependencies.rpg_mobs_pack_1]]
modId="neoforge"
type="required"
versionRange="[21,)"
side="BOTH"
[[dependencies.rpg_mobs_pack_1]]
modId="rpg_core"
type="required"
versionRange="[1.0.0,2.0.0)"
side="BOTH"
