modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mods]]
modId="rpg_content_prontera"
version="${version}"
displayName="RPG Content: Prontera Pack"
description='''Ciudad base + Field1 + Field2 + hooks de dungeon'''
[[dependencies.rpg_content_prontera]]
modId="neoforge"
type="required"
versionRange="[21,)"
side="BOTH"
[[dependencies.rpg_content_prontera]]
modId="rpg_core"
type="required"
versionRange="[1.0.0,2.0.0)"
side="BOTH"
