modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="rpg_core"
version="${version}"
displayName="RPG Core"
description='''
Motor base para el RPG (quests, progreso, etc.).
'''

[[dependencies.rpg_core]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"
