modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="rpg_core"
version="${version}"
displayName="RPG Core"
description='''Engine RPG: stats/xp/economía/warps/quests API'''

[[dependencies.rpg_core]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"
